[project]
name = "mochi-api"
version = "0.1.0"
description = "API integration for Mochi flashcards with Beeminder"
requires-python = ">=3.9"
dependencies = [
    "httpx>=0.27.0"
]

[tool.ruff]
line-length = 88
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "UP"]
